<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element"> <span>
                        <img alt="image" class="img-circle" src="/FormBuilder/public/img/users/<?= $_SESSION['user']["username"] ?>.jpeg" style="width: 40px;" />
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"><?= $_SESSION['user']['username'] ?></strong>
                            </span> <span class="text-muted text-xs block">Art Director <b class="caret"></b></span> </span> </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="contacts.html">Contacts</a></li>
                        <li><a href="mailbox.html">Mailbox</a></li>
                        <li class="divider"></li>
                        <li><a href="login.html">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>

            <li>
                <a href="/FormBuilder/dashboard/test2/"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Dashboard</span> <span class="fa arrow"></span></a>

            </li>

            <li>
                <a href="/FormBuilder/inbox/inbox/"><i class="fa fa-envelope"></i> <span class="nav-label">Inbox</span></a>
            </li>

            <li>
                <a href="/core/workflow/getSteps/"><i class="fa fa-edit"></i><span class="nav-label">Designer</span> <span class="fa arrow"></span></a>

            </li>
            
            <li>
                <a href="/core/users"><i class="fa fa-user"></i><span class="nav-label">User Management</span> <span class="fa arrow"></span></a>

            </li>
            
            <li>
                <a href="/FormBuilder/scheduler/kanban"><i class="fa fa-calendar"></i><span class="nav-label">Kanban</span> <span class="fa arrow"></span></a>

            </li>
            
            <li>
                <a href="/FormBuilder/files"><i class="fa fa-file-archive-o"></i><span class="nav-label">File Manager</span> <span class="fa arrow"></span></a>

            </li>
        </ul>
    </div>
</nav>
