<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Archive Cases</h2>

    </div>
    <div class="col-lg-2">

    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight ecommerce">


    <div class="ibox-content m-b-sm border-bottom">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="order_id">Order ID</label>
                    <input type="text" id="order_id" name="order_id" value="" placeholder="Order ID" class="form-control">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="status">Order status</label>
                    <input type="text" id="status" name="status" value="" placeholder="Status" class="form-control">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="customer">Customer</label>
                    <input type="text" id="customer" name="customer" value="" placeholder="Customer" class="form-control">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="date_added">Date added</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input id="date_added" type="text" class="form-control" value="03/04/2014">
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="date_modified">Date modified</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input id="date_modified" type="text" class="form-control" value="03/06/2014">
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="amount">Amount</label>
                    <input type="text" id="amount" name="amount" value="" placeholder="Amount" class="form-control">
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">

                    <table class="footable table table-stripped toggle-arrow-tiny default footable-loaded" data-page-size="15">
                        <thead>
                            <tr>
                                <th class="footable-visible footable-first-column footable-sortable">App ID<span class="footable-sort-indicator"></span></th>
                                <th class="footable-visible footable-first-column footable-sortable">Case ID<span class="footable-sort-indicator"></span></th>
                                <th data-hide="phone" class="footable-visible footable-sortable">Case Title<span class="footable-sort-indicator"></span></th>
                                <th data-hide="phone" class="footable-visible footable-sortable">User<span class="footable-sort-indicator"></span></th>
                                <th data-hide="phone" class="footable-visible footable-sortable">Process<span class="footable-sort-indicator"></span></th>
                                <th data-hide="phone" class="footable-visible footable-sortable">Date added<span class="footable-sort-indicator"></span></th>
                                <th data-hide="phone,tablet" class="footable-visible footable-sortable">Finish Date<span class="footable-sort-indicator"></span></th>
                                <th class="text-right footable-visible footable-last-column footable-sortable">Action<span class="footable-sort-indicator"></span></th>

                            </tr>
                        </thead>
                        <tbody>

                            <?php foreach ($arrCases['data'] as $objCase): ?>

                                <tr class="footable-even" style="display: table-row;">
                                    
                                     <td class="footable-visible footable-first-column"><span class="footable-toggle"></span>
                                        <?= $objCase->getParentId () ?>
                                    </td>
                                    
                                    <td class="footable-visible footable-first-column"><span class="footable-toggle"></span>
                                        <?= $objCase->getId () ?>
                                    </td>
                                    <td class="footable-visible">
                                        <?= $objCase->getName () ?>
                                    </td>
                                    <td class="footable-visible">
                                        <?= $objCase->getAddedBy () ?>
                                    </td>
                                    <td class="footable-visible">
                                        <?= $objCase->getWorkflowName () ?>
                                    </td>
                                    <td class="footable-visible">
                                        03/05/2015
                                    </td>
                                    <td class="footable-visible">
                                        <?= $objCase->getDateCompleted () ?>
                                    </td>
                                    <td class="text-right footable-visible footable-last-column">
                                        <div class="btn-group">
                                            <button parentId="<?= $objCase->getParentId () ?>" caseId="<?= $objCase->getId () ?>" class="btn-warning btn btn-xs archive">Archive</button>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>

                            <?php foreach ($archivedCases as $archivedCase): ?>
                                <tr class="footable-even" style="display: table-row;">
                                    <td class="footable-visible footable-first-column"><span class="footable-toggle"></span>
                                        <?= $archivedCase['APP_UID'] ?>
                                    </td>
                                    <td class="footable-visible">
                                        <?= $archivedCase['APP_TITLE'] ?>
                                    </td>
                                    <td class="footable-visible">
                                        <?= $archivedCase['USR_UID'] ?>
                                    </td>
                                    <td class="footable-visible">
                                        <?= $archivedCase['APP_PRO_TITLE'] ?>
                                    </td>
                                    <td class="footable-visible">
                                        03/05/2015
                                    </td>
                                    <td class="footable-visible">
                                        <?= $archivedCase['APP_FINISH_DATE'] ?>
                                    </td>
                                    <td class="text-right footable-visible footable-last-column">
                                        <div class="btn-group">
                                            <button parentId="<?= $archivedCase['APP_NUMBER'] ?>" caseId="<?= $archivedCase['APP_UID'] ?>" class="btn-success btn btn-xs restore">Restore</button>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>


                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="7" class="footable-visible">
                                    <ul class="pagination pull-right"><li class="footable-page-arrow disabled"><a data-page="first" href="#first">«</a></li><li class="footable-page-arrow disabled"><a data-page="prev" href="#prev">‹</a></li><li class="footable-page active"><a data-page="0" href="#">1</a></li><li class="footable-page"><a data-page="1" href="#">2</a></li><li class="footable-page"><a data-page="2" href="#">3</a></li><li class="footable-page-arrow"><a data-page="next" href="#next">›</a></li><li class="footable-page-arrow"><a data-page="last" href="#last">»</a></li></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
    </div>


</div>

<script>
    $ (".archive").on ("click", function ()
    {
        var parentId = $ (this).attr ("parentId");
        var caseId = $ (this).attr ("caseId");

        $.ajax ({
            type: "POST",
            url: "/FormBuilder/enterprise/saveArchive/",
            data: {"caseId": caseId, "parentId": parentId},
            success: function (response)
            {
                if ($.trim (response) === "")
                {
                    swal ({
                        title: "Success!",
                        text: response,
                        type: "success"
                    });

                }
                else
                {
                    swal ({
                        title: "Cases could not be routed",
                        text: response,
                        type: "warning",
                        showCancelButton: false
                    });
                }
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    });

    $ (".restore").on ("click", function ()
    {
        var parentId = $ (this).attr ("parentId");
        var caseId = $ (this).attr ("caseId");

        $.ajax ({
            type: "GET",
            url: "/FormBuilder/enterprise/restoreArchive?parentId=" + parentId,
            success: function (response)
            {
                if ($.trim (response) === "")
                {
                    swal ({
                        title: "Success!",
                        text: response,
                        type: "success"
                    });

                }
                else
                {
                    swal ({
                        title: "Cases could not be routed",
                        text: response,
                        type: "warning",
                        showCancelButton: false
                    });
                }
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    });
</script>