<div class="col-lg-12">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Register</h5>

        </div>
        <div class="ibox-content">
            <form id="userRegisterForm" name="userRegisterForm" class="form-horizontal">

                <div class="form-group">
                    <label class="col-lg-2 control-label">Firstname</label>

                    <div class="col-lg-10">
                        <input name="firstName" type="text" placeholder="First Name" class="form-control"> 
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label">Lastname</label>

                    <div class="col-lg-10">
                        <input name="lastName" type="text" placeholder="Last Name" class="form-control"> 
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label">Email</label>

                    <div class="col-lg-10">
                        <input id="user_email" name="user_email" type="text" placeholder="Email" class="form-control"> 
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label">Username</label>

                    <div class="col-lg-10">
                        <input name="username" type="text" placeholder="Username" class="form-control"> 
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label">Password</label>

                    <div class="col-lg-10">
                        <input id="password" name="password" type="password" placeholder="Password" class="form-control">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label">Confirm Password</label>

                    <div class="col-lg-10">
                        <input id="confirmPassword" name="confirmPassword" type="password" placeholder="Confirm Password" class="form-control">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button class="btn btn-sm btn-white register" type="submit">Register</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="col-lg-12 pull-left responseBox">

</div>

<script>

    function validateEmail (email)
    {
        var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test (email);
    }

    function validateFieldsEmpty ()
    {
        var isValid;
        $ ("input").each (function ()
        {
            var element = $ (this);
            if (element.val () == "")
            {
                isValid = false;
            }
        });

        return isValid;
    }

    $ (".register").on ("click", function ()
    {
        var formData = $ ("#userRegisterForm").serialize ();

        if (!validateFieldsEmpty ())
        {
            alert ("All fields must be completed");
            return false;
        }


        if ($.trim ($ ("#password").val ()) !== $.trim ($ ("#confirmPassword").val ()))
        {
            alert ("Passwords do not match");
            return false;
        }

        if (!validateEmail ($ ("#user_email").val ()))
        {
            alert ("Incorrect email address given!");
            return false;
        }

        $.ajax ({
            type: "POST",
            data: formData,
            url: "/FormBuilder/enterprise/saveRegisterUser/",
            success: function (response)
            {
                $ (".responseBox").html (response);

            }
        });

        return false;
    });

</script>