
<style>

a:link, a:visited { 
	color: #000000; 
	text-decoration: none; 
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 12px; 
	font-style: normal; 
	font-weight: none;
	background-color: none; }
a:hover {
	color: #000000; 
	text-decoration: underline; 
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 12px; 
	font-style: normal; 
	font-weight: none;
	background-color: none; 
	}

INPUT {

background-color: #FFFFCC;

border: #FFCC00 1px solid;

color: #333333;

font-family: verdana;

font-size: 8pt

} 



.altButtonFormat {

background-color: #FFCC00;

font-family: verdana;

border: #FFCC00 1px solid;

font-weight: bold;

font-size: 10px;

color: #333333
} 

.mxbOnlineTextBlue { 
font-family: Arial, Helvetica, sans-serif; 
font-size: 16px;
 font-style: normal; 
font-weight: bold; 
color: #004474; 
text-decoration: none 
}


.langLink {  font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; font-style: normal; font-weight: normal; color: #003366; text-decoration: none}
.navOff { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-weight: normal; color: #003366; text-decoration: none }
.navOn { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-weight: normal; color: #6699CC; text-decoration: none }
.news { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-weight: normal; color: #336699; text-decoration: none }
.newsArchive { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-weight: normal; color: #669933; text-decoration: none }
.mainBackgr {  background-attachment: scroll; background-image: url(../images/mainBackgr.gif); background-repeat: no-repeat; background-position: right top}
.mxbOnlineText { font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-weight: bold; color: #FFFFFF; text-decoration: none }
.mxbOnlineLink { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; font-style: normal; font-weight: normal; color: #FFCC00; text-decoration: none }
.mainCopy {  font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-weight: normal; color: #333333}
.copyright {  font-fami
</style>

<body>
<table width="100%" height="95" border="0" cellpadding="0" cellspacing="0" bgcolor="#003366">
  <tr>
    <td width="15%" align="center" scope="col"><img src="library/logo.gif"></td>
    <td width="67%" scope="col">&nbsp;</td>
    <td width="18%" class="mxbOnlineText" scope="col"><?php echo $ERROR_TEXT ?></td>
  </tr>
  <tr>
    <td height="12" colspan="3" align="center" bgcolor="#336699" scope="col"></td>
  </tr>
</table>
<br />
<br />
<table width="70%" border="0" align="center" cellpadding="0" cellspacing="0" class="mainCopy">
  <tr>
    <td width="15%" align="left" scope="col"><span class="mxbOnlineTextBlue"><?php echo $ERROR_TEXT ?> </span><br />
    <?php echo $ERROR_DESCRIPTION ?>
  </tr>
</table>
</body>
</html>
