<div class="col-lg-12 pull-left">
    <?= $pagination ?> 
</div>

<div class="col-lg-12 pull-left">

    <div class="input-group col-lg-4" style="margin-bottom: 12px;">
        <input type="text" id="processSearchText" placeholder="Search Workflow " class="input form-control">
    </div>

    <div class="client-detail col-lg-4 processesList" style="background-color: #FFF; padding-top: 10px;">
        <?php
        $requestId = null;
        foreach ($arrWorkflows as $objWorkflow) {
            ?>

            <?php
            if ( $requestId === null || $requestId !== $objWorkflow->getRequestId () )
            {
                echo '</ul><ul class="list-group clear-list">'
                . '<strong>' . $objWorkflow->getcategoryName () . '</strong>';

                $end = true;
            }
            ?>

            <li workflowid="<?= $objWorkflow->getId () ?>" class="list-group-item fist-item" style="border-bottom: 1px dotted #CCC;">
                <span class="pull-right"> 
                    <button workflowid="<?= $objWorkflow->getId () ?>" type="button" class="btn btn-primary btn-xs addNewCase">+</button> 
                </span>
                <?= $objWorkflow->getworkflowName () ?>
            </li>

            <?php
            $requestId = $objWorkflow->getRequestId ();
            $end = false;
        }
        ?>
    </div>

    <div class="col-lg-8 pull-left casesList">

    </div>
</div>




<script>

    $ ("#processSearchText").on ("keyup", function ()
    {
        var searchText = $ (this).val ();
        var workflowId = $ (".selectedRow").attr ("workflowid");

        $.ajax ({
            type: "POST",
            data: {"searchText": searchText},
            url: "/FormBuilder/inbox/filterProcesses/",
            success: function (response)
            {
                $ (".processesList").html (response);
                //rebind ();
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    });


    $ (".addNewCase").on ("click", function ()
    {
        var workflowid = $ (this).attr ("workflowid");

        $.ajax ({
            type: "GET",
            url: "/FormBuilder/inbox/addNewCase/" + workflowid,
            success: function (response)
            {
                $ ("#myModal6").html (response).modal ("show");
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    });

    $ (".list-group-item").on ("click", function ()
    {
        $ (".list-group-item").removeClass ("selectedRow");
        $ (this).addClass ("selectedRow");

        var workflowid = $ (this).attr ("workflowid");

        $.ajax ({
            type: "GET",
            url: "/FormBuilder/inbox/filterCases/" + workflowid,
            success: function (response)
            {
                $ (".casesList").html (response);

                $ (".searchCases").on ("click", function ()
                {
                    $.ajax ({
                        type: "GET",
                        url: "/FormBuilder/inbox/searchCases/0/element_id/ASC/" + $ ("#caseSearchText").val (),
                        success: function (response)
                        {
                            $("#tab-1 > .table-responsive").html(response);
                        }, error: function (request, status, error)
                        {
                            alert (status + ' ' + error);
                        }
                    });
                });

                $ (".reassignUsers").on ("click", function ()
                {
                    //var parentId = $ (this).parent ().parent ().attr (projectid);

                    $.ajax ({
                        type: "GET",
                        url: "/FormBuilder/inbox/reassignUsers/",
                        success: function (response)
                        {
                            $ ("#reassignUsersModal").html (response).modal ("show");
                        }
                        , error: function (request, status, error)
                        {
                            alert (status + ' ' + error);
                        }
                    });
                });

                $ (".openSummary").on ("click", function ()
                {
                    var parentId = $ (this).parent ().parent ().attr ('projectid');
                    
                    alert("Here");

                    $.ajax ({
                        type: "GET",
                        url: "/FormBuilder/inbox/openSummary/" + parentId,
                        success: function (response)
                        {
                            $ ("#summaryModal").html (response).modal ("show");
                        }, error: function (request, status, error)
                        {
                            alert (status + ' ' + error);
                        }
                    });
                    
                    return false;
                });


                $ (".caseRow").on ("click", function ()
                {
                    var projectId = $ (this).parent().attr ("projectid");

                    getProjectDetails (projectId);
                });
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        }
        );
    });

    function getProjectDetails (projectId)
    {
        alert (projectId);
        $ ("#createProject").html ("");
        $.ajax ({
            type: "GET",
            url: "/FormBuilder/index/getProject/" + projectId,
            success: function (response)
            {
                console.log (response);
                $ ("#myModal7").html (response).modal ("show");
            }, error: function (request, status, error)
            {
                alert (status + ' ' + error);
            }
        });
    }

</script>