<?php
if ( empty ($arrCases) )
{
    echo '<br><br><br><center><h2>No Cases could be found </h2></center>';
    exit;
}
?>

<div class="col-lg-12 pull-left">
<?= $pagination ?>
</div>

<table class="table table-hover table-mail">

    <thead>
        <tr>
            <th></th>
            <th>Case Id</th>
            <th>Project Id</th>
            <th>Case Name</th>
            <th>Process</th>
            <th>Step Name</th>
            <th>Current User</th>
        </tr>
    </thead>

    <tbody>

<?php foreach ($arrCases['data'] as $key => $arrCase): ?>

            <tr class="mailItem">
                <td id="<?= $arrCase->getId () ?>" class="check-mail">
                    <input type="checkbox" class="i-checks">
                </td>
                <td><?= $arrCase->getId () ?></td>
                <td><?= $arrCase->getParentId () ?></td>
                <td><?= $arrCase->getName () ?></td>
                <td><?= $arrCase->getWorkflowName () ?></td>
                <td><?= $arrCase->getCurrent_step () ?></td>
                <td><?= $arrCase->getCurrent_user () ?></td>
            </tr>

<?php endforeach; ?>

    </tbody>
</table>