<?php
$requestId = null;
foreach ($arrWorkflows['data'] as $objWorkflow) {
    ?>

    <?php
    if ( $requestId === null || $requestId !== $objWorkflow->getRequestId () )
    {
        echo '</ul><ul class="list-group clear-list">'
        . '<strong>' . $objWorkflow->getcategoryName () . '</strong>';

        $end = true;
    }
    ?>

    <li workflowid="<?= $objWorkflow->getId () ?>" class="list-group-item fist-item" style="border-bottom: 1px dotted #CCC;">
        <span class="pull-right"> 
            <button workflowid="<?= $objWorkflow->getId () ?>" type="button" class="btn btn-primary btn-xs addNewCase">+</button> 
        </span>
        <?= $objWorkflow->getworkflowName () ?>
    </li>

    <?php
    $requestId = $objWorkflow->getRequestId ();
    $end = false;
}
?>