
<?php

function buildCounters ($arrCounters, $strType = 'DEFAULT')
{
    $arrColours = array("text-navy", "text-danger", "text-primary", "text-info", "text-warning", "text-primary", "text-info", "text-warning", "text-warning", "text-primary", "text-info", "text-warning");
    $html = '';
    foreach ($arrCounters as $key => $arrCounter):


        if ( $arrCounter['item'] == "CASES_INBOX" && $strType == "CASES_INBOX" )
        {
            return $arrCounter['count'];
        }
        elseif ( $arrCounter['item'] == "CASES_DRAFT" && $strType == "CASES_DRAFT" )
        {
            return $arrCounter['count'];
        }
        else
        {
            $html .= '<li><a list-type="' . $arrCounter['item'] . '" href="#"> <i class="fa fa-circle ' . $arrColours[$key] . '"></i> ' . $arrCounter['item'] . " (" . $arrCounter['count'] . ") " . '</a></li>';
        }

    endforeach;

    return $html;
}
?>

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-2">
            <div class="ibox float-e-margins">
                <div class="ibox-content mailbox-content">

                    <?php $showBatchRouting = 1; ?>

                    <div class="file-manager">
                        <div class="space-25"></div>
                        <h5>Folders</h5>
                        <ul class="folder-list m-b-md" style="padding: 0">
                            <li><a class="addProcess" href="#"> <i class="fa fa-plus-square"></i> New Case</a></li>
                            <li><a class="changeStatus" status="1" href="#"> <i class="fa fa-inbox "></i> Inbox <span class="label label-warning pull-right"><?= buildCounters ($arrCounters, "CASES_INBOX") ?></span> </a></li>
                            <li><a class="changeStatus" href="#"> <i class="fa fa-envelope-o"></i> Send Mail</a></li>

                            <?php
                            if ( $showBatchRouting === 1 )
                            {
                                echo '<li><a class="batchRouting" status="8" href="#" href="mailbox.html"> <i class="fa fa-certificate"></i> Batch Routing</a></li>';
                            }
                            ?>

                            <li><a class="changeStatus" status="8" href="#" href="mailbox.html"> <i class="fa fa-certificate"></i> Important</a></li>
                            <li><a class="changeStatus" href="#" status="2" href="mailbox.html"> <i class="fa fa-file-text-o"></i> Drafts <span class="label label-danger pull-right"><?= buildCounters ($arrCounters, "CASES_DRAFT") ?></span></a></li>
                            <li><a class="changeStatus" href="#" href="mailbox.html"> <i class="fa fa-trash-o"></i> Trash</a></li>
                            <li><a class="changeStatus" href="#" status="3" href="#"> <i class="fa fa-trash-o"></i> Archived</a></li>
                        </ul>

                        <h5>Search</h5>
                        <ul class="folder-list m-b-md" style="padding: 0">
                            <li><a class="advancedSearch" href="#"> <i class="fa fa-search"></i> Advanced Search</a></li>
                        </ul>

                        <h5>Categories</h5>
                        <ul class="category-list" style="padding: 0">
<?= buildCounters ($arrCounters); ?>


                        </ul>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-lg-10 animated fadeInRight mainContentWrapper">
            <div class="mail-box-header">

                <form method="get" action="index.html" class="pull-right mail-search">
                    <div class="input-group">
                        <input type="text" class="form-control input-sm" id="search" name="search" placeholder="Search email">
                        <div class="input-group-btn">
                            <button type="button" id="Search" class="btn btn-sm btn-primary">
                                Search
                            </button>
                        </div>
                    </div>
                </form>
                <h2>
                    Inbox (<?= count ($arrNotifications) ?>)
                </h2>
                <div class="mail-tools tooltip-demo m-t-md">

                    <button class="btn btn-white btn-sm" data-toggle="tooltip" data-placement="left" title="Refresh inbox"><i class="fa fa-refresh"></i> Refresh</button>
                    <button class="btn btn-white btn-sm updateStatus" status="5" data-toggle="tooltip" data-placement="top" title="Mark as read"><i class="fa fa-eye"></i> </button>
                    <button class="btn btn-white btn-sm updateStatus" status="6" data-toggle="tooltip" data-placement="top" title="Mark as important"><i class="fa fa-exclamation"></i> </button>
                    <button class="btn btn-white btn-sm updateStatus" status="4" data-toggle="tooltip" data-placement="top" title="Move to trash"><i class="fa fa-trash-o"></i> </button>

                </div>
            </div>
            <div class="mail-box">




            </div>
        </div>
    </div>
</div>

<div class="modal inmodal fade" id="myModal6" tabindex="-1" role="dialog"  aria-hidden="true">
</div>

<div class="modal inmodal fade" id="myModal7" tabindex="-1" role="dialog"  aria-hidden="true">
</div>

<div class="modal inmodal fade" id="summaryModal" tabindex="-1" role="dialog"  aria-hidden="true">
</div>

<div class="modal inmodal fade" id="reassignUsersModal" tabindex="-1" role="dialog"  aria-hidden="true">
</div>

<script src="/FormBuilder/public/js/plugins/iCheck/icheck.min.js"></script>

<script>
    var selected = [];
    var page = 0;
    var orderBy = "ns.APP_MSG_SEND_DATE";
    var orderDir = "DESC";
    var status = 1;
    var listType = null;
    var processPage = 0;

    function projectsPage (selectedPage)
    {
        page = selectedPage;

        $.ajax ({
            type: "GET",
            url: "/FormBuilder/inbox/filterProjects/" + listType + "/" + page,
            success: function (response)
            {
                $ (".mail-box").html (response);
                rebind ();
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    }

    $ (".batchRouting").off ();
    $ (".batchRouting").on ("click", function ()
    {
        $.ajax ({
            type: "GET",
            url: "/FormBuilder/inbox/batchRouting/",
            success: function (response)
            {
                alert(response);
                $ (".mail-box").html (response);
                $ (".mail-box-header").hide ();
                rebind ();
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    });

    $ (".advancedSearch").off ();
    $ (".advancedSearch").on ("click", function ()
    {
        $.ajax ({
            type: "GET",
            url: "/FormBuilder/inbox/advancedSearch/",
            success: function (response)
            {
                $ (".mail-box").html (response);
                $ (".mail-box-header").hide ();
                rebind ();
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    });

    $ (".category-list > li > a").off ();
    $ (".category-list > li > a").on ("click", function ()
    {
        listType = $ (this).attr ("list-type");
        page = 0;

        $.ajax ({
            type: "GET",
            url: "/FormBuilder/inbox/filterProjects/" + listType + "/" + page,
            success: function (response)
            {
                $ (".mail-box").html (response);
                rebind ();
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    });

    function rebind ()
    {
        $ ('.i-checks').iCheck ({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });

        $ ('.i-checks').on ('ifChecked', function (event)
        {
            var id = $ (this).parent ().parent ().attr ("id");
            selected.push (id);
            console.log (id);
        });

        $ (".mailItem").on ("click", function ()
        {
            var id = $ (this).find (".check-mail").attr ("id");

            $.ajax ({
                type: "GET",
                url: "/FormBuilder/inbox/getMessage/" + id,
                success: function (response)
                {
                    $ (".mainContentWrapper").html (response);
                    rebind ();
                },
                error: function (request, status, error)
                {
                    console.log ("critical errror occured");
                }
            });

            return false;
        });
    }

    function search ()
    {
        var searchText = $ ("#search").val ();

        $.ajax ({
            type: "POST",
            url: "/FormBuilder/inbox/searchMessages/" + status + "/" + page + "/" + orderBy + "/" + orderDir,
            data: {"searchText": searchText},
            success: function (response)
            {
                $ (".mail-box-header").show ();
                $ (".mail-box").html (response);
                rebind ();
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    }

    function searchProcesses ()
    {
        $.ajax ({
            type: "GET",
            url: "/FormBuilder/inbox/addCase/" + processPage,
            success: function (response)
            {
                $ (".mail-box-header").hide ();
                $ (".mail-box").html (response);
                rebind ();
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    }

    function processPagination (page)
    {
        processPage = page;
        searchProcesses ();
    }

    function jumpToPage (pageNo)
    {
        page = pageNo;
        search ();
    }

    $ (document).ready (function ()
    {
        search ();

        $ ("#Search").on ("click", function ()
        {
            search ();
        });

        $ (".addProcess").on ("click", function ()
        {
            if ($ (this).hasClass ("selected"))
            {
                $ (this).removeClass ("selected");
                search ();
                return false;
            }

            $ (this).addClass ("selected");
            searchProcesses ();


        });

        $ ('.cd-panel').on ('click', function (event)
        {
            if ($ (event.target).is ('.cd-panel') || $ (event.target).is ('.cd-panel-close'))
            {
                $ ('.cd-panel').removeClass ('is-visible');
                event.preventDefault ();
            }
        });

        rebind ();

        $ (".updateStatus").on ("click", function ()
        {
            var status = $ (this).attr ("status");

            $.ajax ({
                type: "POST",
                data: {"selected": selected},
                url: "/FormBuilder/inbox/updateStatus/" + status,
                success: function (response)
                {
                    alert (response);
                },
                error: function (request, status, error)
                {
                    console.log ("critical errror occured");
                }
            });
        });

        $ (".changeStatus").on ("click", function ()
        {
            status = $ (this).attr ("status");
            page = 0;

            search ();
        });
    });

</script>