<div class="modal-dialog">
    <div class="modal-content animated bounceInRight">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <i class="fa fa-laptop modal-icon"></i>
            <h4 class="modal-title">Case Summary</h4>
        </div>
        <div class="modal-body">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Summary</h5>
                    </div>

                    <div class="ibox-content">
                        <div class="panel-body">
                            <div class="panel-group" id="accordion">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h5 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" class="">Case Properties</a>
                                        </h5>
                                    </div>
                                    <div id="collapseOne" class="panel-collapse collapse in" aria-expanded="true" style="">
                                        <div class="panel-body">
                                            <ul>
                                                <li><strong>Process</strong> <?= $objCase->getWorkflowName () ?></li>
                                                <li><strong>Case Title</strong> <?= $objCase->getName () ?></li>
                                                <li><strong>Project Id</strong><?= $objCase->getParentId () ?></li>
                                                <li><strong>Case Status</strong> <?= $objCase->getStatus () ?></li>
                                                <li><strong>Case Uid</strong><?= $objCase->getId () ?></li>
                                                <li><strong>Creator</strong> <?= $objCase->getAddedBy () ?></li>
                                                <li><strong>Create Date</strong> <?= $objCase->getName () ?></li>
                                                <li><strong>Case Description</strong> <?= $objCase->getDescription () ?></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" class="collapsed" aria-expanded="false">Current Task Properties</a>
                                        </h4>
                                    </div>
                                    <div id="collapseTwo" class="panel-collapse collapse" aria-expanded="false">
                                        <div class="panel-body">
                                            <ul>
                                                <li><strong>Task</strong> <?= $objCase->getCurrent_step () ?></li>
                                                <li><strong>Current User</strong> <?= $objCase->getCurrent_user () ?></li>
                                                <li><strong>Init Date</strong> <?= $audit['dateCompleted'] ?></li>
                                                <li><strong>Due Date</strong> <?= $audit['due_date'] ?></li>
                                                <li><strong>Finish Date</strong> <?= $audit['finish_date'] ?></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>



