<div class="modal-dialog">
    <div class="modal-content animated bounceInRight">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <i class="fa fa-laptop modal-icon"></i>
            <h4 class="modal-title">Re-assign User</h4>
        </div>
        <div class="modal-body">
            <div class="ibox-content">
                <form class="form-horizontal" id="reassignForm">
                    <input type="hidden" id="APP_UID" value="<?= $appUid ?>" name="APP_UID">
                    <input type="hidden" id="DEL_INDEX" value="<?= $taskId ?>" name="DEL_INDEX">
                    <p>Choose a user to re-assign.</p>

                    <div class="form-group">
                        <label class="col-lg-2 control-label">Users</label>

                        <div class="col-lg-10">
                            <select class="form-control" name="userId" id="userId">
                                <option value=""></option>
                                <?php
                                foreach ($response['resultRoot'] as $user):
                                    $name = $user['firstName'] . " " . $user['lastName'] . " (" . $user['username'] . ")";
                                    ?>
                                    <option value="<?= $user['usrid'] ?>"><?= $name ?></option>
                                <?php endforeach; ?>

                            </select>
                        </div>
                    </div>

                </form>
            </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary SaveReassign">Save</button>
        </div>
    </div>
</div>

<script>
    $ (".SaveReassign").on ("click", function ()
    {
        var formData = $("#reassignForm").serialize();
        
        $.ajax ({
            type: "POST",
            data: formData,
            url: "/FormBuilder/inbox/saveReassignUser/",
            success: function (response)
            {
               alert(response);
                //rebind ();
            },
            error: function (request, status, error)
            {
                console.log ("critical errror occured");
            }
        });
    });
</script>




