<div class="col-lg-12 pull-left">
    <?= $pagination ?>
</div>

<?php
if ( empty ($arrNotifications) )
    echo '<center><h2>No Notifications could be found.</h2><center>';
?>

<table class="table table-hover table-mail">

    <thead>
        <tr>
            <th></th>
            <th>Case Id</th>
            <th>Case Name</th>
            <th>Subject</th>
            <th>Step</th>
            <th>Process</th>
            <th>Due Date</th>

            <?php
            if ( count ($customFields) > 0 )
            {
                foreach ($customFields as $customField) {
                    echo '<th>' . $customField . '</th>';
                }
            }
            ?>
<!--            <th>Date Sent</th>-->
        </tr>
    </thead>

    <tbody>

        <?php
        foreach ($arrNotifications as $key => $arrNotification):

            if ( is_object ($arrNotifications[$key]['project']) ):

                $class = $arrNotification['notifications']->getHasRead () == 0 ? 'unread' : 'read';
                ?>

                <tr class="<?= $class ?> mailItem">
                    <td id="<?= $arrNotification['notifications']->getAppMsgUid () ?>" class="check-mail">
                        <input type="checkbox" class="i-checks">
                    </td>
                    <td class=""><?= $arrNotification['project']->getId () ?></td>
                    <td class="mail-subject"><a href="mail_detail.html"><?= $arrNotifications[$key]['project']->getName () ?></a></td>
                    <td class="mail-ontact"><a href="mail_detail.html"><?= $arrNotification['notifications']->getAppMsgSubject () ?></a></td>
                    <td class=""><?= $arrNotification['project']->getCurrent_step () ?></td>
                    <td class=""><?= $arrNotification['project']->getWorkflowName () ?></td>

                        <!--                <td class="text-right mail-date"><?= $arrNotification['notifications']->getAppMsgSendDate () ?></td>-->
                    <td class=""><?= $arrNotification['project']->getDueDate () ?></td>

                    <?php
                    if ( count ($customFields) > 0 )
                    {
                        foreach ($arrNotification['custom_fields'] as $customField) {
                            echo '<td>' . $customField . '</td>';
                        }
                    }
                    ?>

                </tr>

        <?php
    endif;
endforeach;
?>

    </tbody>
</table>