<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title"> Project #<?= $projectId ?></h4>

        </div>
        <div class="modal-body">
            <div class="col-lg-12 m-b-md">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a title="form" data-toggle="tab" href="#tab-3"> Forms</a></li>
                        <li class=""><a title="input" data-toggle="tab" href="#tab-4">Input Documents</a></li>
                        <li class=""><a title="output" data-toggle="tab" href="#tab-5">Output Documents</i></a></li>
                        <?php
                        if ( isset ($arrCaseTracker['routing_history']) && (int) $arrCaseTracker['routing_history'] === 1 )
                        {
                            echo ' <li class=""><a title="history" data-toggle="tab" href="#tab-6">My Messages</a></li>';
                        }

                        if ( isset ($arrCaseTracker['message_history']) && (int) $arrCaseTracker['message_history'] === 1 )
                        {
                            echo ' <li class=""><a title="history" data-toggle="tab" href="#tab-7">Case History</a></li>';
                        }
                        ?>

                    </ul>
                    <div class = "tab-content">
                        <div id = "tab-3" class = "tab-pane active">
                            <div class = "panel-body">
                                <h2>Form</h2>

                                <? = $html
                                ?>
                            </div>
                        </div>
                        <div id="tab-4" class="tab-pane">
                            <div class="panel-body">
                                <h2>Input</h2>

                                <?php
                                if ( isset ($arrAttachments['INPUT']) && !empty ($arrAttachments['INPUT']) )
                                {
                                    foreach ($arrAttachments['INPUT'] as $arrObject):
                                        if ( $arrObject['status'] !== "DELETED" )
                                        {
                                            echo '<div class="file-box">
                                 <a href="' . str_replace("C:/xampp/htdocs", "", $arrObject['path']) . '">
                                 <div class="file">
                                   
                                        <span class="corner"></span>

                                        <div class="icon">
                                            <i class="fa fa-file"></i>
                                        </div>
                                        <div class="file-name">
                                            ' . $arrObject['filename'] . '
                                            <br>
                                            <small>Added: ' . $arrObject['date_created'] . '</small>
                                        </div>
                                    
                                </div>
                                </a>

                            </div>';
                                        }

                                    endforeach;
                                }
                                ?>
                            </div>
                        </div>
                        <div id="tab-5" class="tab-pane">
                            <div class="panel-body">
                                <h2>Output</h2>

                                <?php
                                if ( isset ($arrAttachments['OUTPUT']) && !empty ($arrAttachments['OUTPUT']) )
                                {
                                    foreach ($arrAttachments['OUTPUT'] as $arrObject):
                                        if ( $arrObject['status'] !== "DELETED" )
                                        {
                                            echo '<div class="file-box">
                                 <a href="' . str_replace("C:/xampp/htdocs", "", $arrObject['path']) . '">
                                 <div class="file">
                                   
                                        <span class="corner"></span>

                                        <div class="icon">
                                            <i class="fa fa-file"></i>
                                        </div>
                                        <div class="file-name">
                                            ' . $arrObject['filename'] . '
                                            <br>
                                            <small>Added: ' . $arrObject['date_created'] . '</small>
                                        </div>
                                    
                                </div>
                                </a>

                            </div>';
                                        }

                                    endforeach;
                                }
                                ?>
                            </div>
                        </div>

                        <div id="tab-6" class="tab-pane">
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">

                                        <thead>
                                        <th>Date Sent</th>
                                        <th>Sent By</th>
                                        <th>Subject</th>
                                        <th>Step</th>
                                        </thead>
                                        <tbody>
                                            <?php
                                            //if ( $arrMessages[0]['project']->getWorkflow_id () === $workflowId )
                                            //{
                                            foreach ($arrMessages as $key => $arrNotification):
                                                if ( isset ($arrNotification['project']) && is_object ($arrNotification['project']) )
                                                {
                                                    ?>
                                                    <tr>
                                                        <td class="mail-ontact"><a href="mail_detail.html"><?= $arrNotification['notifications']->getDateSent () ?></a></td>
                                                        <td><?= $arrNotification['notifications']->getFrom () ?></td>
                                                        <td class="mail-ontact"><a href="mail_detail.html"><?= $arrNotification['notifications']->getSubject () ?></a></td>
                                                        <td class=""><?= $arrNotification['project']->getCurrent_step () ?></td>
                                                    </tr>

                                                    <?php
                                                }
                                            endforeach;
                                            //}
                                            ?>


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <div id="tab-7" class="tab-pane">
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">

                                        <thead>
                                        <th>User</th>
                                        <th>Date Started</th>
                                        <th>Status</th>
                                        <th>Due Date</th>
                                        <th>Date Completed</th>
                                        <th>Step</th>
                                        </thead>

                                        <tbody>
                                            <?php
                                            //if ( $arrMessages[0]['project']->getWorkflow_id () === $workflowId )
                                            //{
                                            foreach ($arrAudit['steps'] as $key => $audit):
                                                ?>
                                                <tr>
                                                    <td class=""><?= $audit['claimed'] ?></td>
                                                    <td class="mail-subject"><a href="mail_detail.html"><?= $audit['dateCompleted'] ?></a></td>
                                                    <td class="mail-ontact"><a href="mail_detail.html"><?= $audit['status'] ?></a></td>
                                                    <td class=""><?= $audit['due_date'] ?></td>
                                                    <td class=""><?= $audit['finish_date'] ?></td>
                                                    <td><?= $key ?></td>

                                                </tr>

                                                <?php
                                            endforeach;
                                            //}
                                            ?>


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>